export { default as NuxtLogo } from '../../components/NuxtLogo.vue'
export { default as AuthenticationLogin2 } from '../../components/Authentication/login-2.vue'
export { default as AuthenticationLogin } from '../../components/Authentication/login.vue'
export { default as AuthenticationSignup2 } from '../../components/Authentication/signup-2.vue'
export { default as AuthenticationSignup } from '../../components/Authentication/signup.vue'
export { default as BlogsDetails } from '../../components/blogs/details.vue'
export { default as BlogsLeftSidebar } from '../../components/blogs/left-sidebar.vue'
export { default as BlogsNoSidebar } from '../../components/blogs/no-sidebar.vue'
export { default as BlogsRightSidebar } from '../../components/blogs/right-sidebar.vue'
export { default as PagenotfoundErrorpage } from '../../components/pagenotfound/errorpage.vue'
export { default as Pagenotfound } from '../../components/pagenotfound/index.vue'
export { default as LandingPageAppDesign } from '../../components/landing-page/app-design.vue'
export { default as LandingPageChitChat } from '../../components/landing-page/chit-chat.vue'
export { default as LandingPageCollaboration } from '../../components/landing-page/collaboration.vue'
export { default as LandingPage } from '../../components/landing-page/index.vue'
export { default as LandingPageOfficial } from '../../components/landing-page/official.vue'
export { default as LandingPagePricingPlan } from '../../components/landing-page/pricing-plan.vue'
export { default as LandingPageSecureApp } from '../../components/landing-page/secure-app.vue'
export { default as LandingPageSlider } from '../../components/landing-page/slider.vue'
export { default as LandingPageSubscribeUpdate } from '../../components/landing-page/subscribe-update.vue'
export { default as LandingPageTeamWork } from '../../components/landing-page/team-work.vue'
export { default as LandingPageTestimonial } from '../../components/landing-page/testimonial.vue'
export { default as MessengerChat } from '../../components/messenger/chat.vue'
export { default as Messenger } from '../../components/messenger/index.vue'
export { default as MessengerLeftSidebar } from '../../components/messenger/left-sidebar.vue'
export { default as MessengerNav } from '../../components/messenger/nav.vue'
export { default as MessengerStickers } from '../../components/messenger/stickers.vue'
export { default as BlogsCommonBlogFollowUs } from '../../components/blogs/Common/blog_follow_us.vue'
export { default as BlogsCommonBlogHeader } from '../../components/blogs/Common/blog_header.vue'
export { default as BlogsCommonBlogMedia } from '../../components/blogs/Common/blog_media.vue'
export { default as BlogsCommonBlogPopular } from '../../components/blogs/Common/blog_popular.vue'
export { default as BlogsCommonBlogRecent } from '../../components/blogs/Common/blog_recent.vue'
export { default as BlogsCommonBlogSearch } from '../../components/blogs/Common/blog_search.vue'
export { default as BlogsCommonBlogTags } from '../../components/blogs/Common/blog_tags.vue'
export { default as BlogsBlogCard } from '../../components/blogs/blog_card/blog_card.vue'
export { default as BlogsBlogDetail } from '../../components/blogs/blog_details/blog_detail.vue'
export { default as BlogsBlogSidebar } from '../../components/blogs/blog_sidebar/blog_sidebar.vue'
export { default as BlogsBlogNoSidebar } from '../../components/blogs/blog_no-sidebar/blog_no-sidebar.vue'
export { default as BlogsComments } from '../../components/blogs/comments/comments.vue'
export { default as BlogsLeaveComments } from '../../components/blogs/leave_coments/leave_comments.vue'
export { default as BonusPageAboutPage } from '../../components/bonus_page/about/about-page.vue'
export { default as BonusPageAboutCounter } from '../../components/bonus_page/about/counter.vue'
export { default as BonusPageAbout } from '../../components/bonus_page/about/index.vue'
export { default as BonusPageElementsBackgroundcolor } from '../../components/bonus_page/elements/backgroundcolor.vue'
export { default as BonusPageElementsBadge } from '../../components/bonus_page/elements/badge.vue'
export { default as BonusPageElementsBadgeWithIcons } from '../../components/bonus_page/elements/badgeWithIcons.vue'
export { default as BonusPageElementsBadgeWithSmallLabelIcon } from '../../components/bonus_page/elements/badgeWithSmallLabelIcon.vue'
export { default as BonusPageElementsBadgeWithTypography } from '../../components/bonus_page/elements/badgeWithTypography.vue'
export { default as BonusPageElementsBadgeWithstatus } from '../../components/bonus_page/elements/badgeWithstatus.vue'
export { default as BonusPageElementsButtonbackground } from '../../components/bonus_page/elements/buttonbackground.vue'
export { default as BonusPageElementsButtons } from '../../components/bonus_page/elements/buttons.vue'
export { default as BonusPageElementsFonts } from '../../components/bonus_page/elements/fonts.vue'
export { default as BonusPageElementsIcons } from '../../components/bonus_page/elements/icons.vue'
export { default as BonusPageElementsImages } from '../../components/bonus_page/elements/images.vue'
export { default as BonusPageElements } from '../../components/bonus_page/elements/index.vue'
export { default as BonusPageElementsLabelFonts } from '../../components/bonus_page/elements/label-fonts.vue'
export { default as BonusPageElementsMainChat } from '../../components/bonus_page/elements/mainChat.vue'
export { default as BonusPageElementsMessageBox } from '../../components/bonus_page/elements/messageBox.vue'
export { default as BonusPageElementsPhoneButton } from '../../components/bonus_page/elements/phoneButton.vue'
export { default as BonusPageElementsSharedDoc } from '../../components/bonus_page/elements/sharedDoc.vue'
export { default as BonusPageElementsSpanParag } from '../../components/bonus_page/elements/span-parag.vue'
export { default as BonusPageElementsThemebuttons } from '../../components/bonus_page/elements/themebuttons.vue'
export { default as BonusPageElementsTypography } from '../../components/bonus_page/elements/typography.vue'
export { default as BonusPageFaq } from '../../components/bonus_page/faq/index.vue'
export { default as BonusPagePriceBonusprice } from '../../components/bonus_page/price/bonusprice.vue'
export { default as BonusPagePrice } from '../../components/bonus_page/price/index.vue'
export { default as CommonBreadcrumbBreadCrumbs } from '../../components/common/breadcrumb/bread_crumbs.vue'
export { default as CommonFooter } from '../../components/common/footer/footer.vue'
export { default as CommonHeader } from '../../components/common/header/header.vue'
export { default as CommonLogo } from '../../components/common/logo/logo.vue'
export { default as CommonNavbar } from '../../components/common/navbar/navbar.vue'
export { default as CommonTapToTopTaptop } from '../../components/common/tap-to-top/taptop.vue'
export { default as MessengerCallsAllcalls } from '../../components/messenger/calls/allcalls.vue'
export { default as MessengerCallsCallcontent } from '../../components/messenger/calls/callcontent.vue'
export { default as MessengerCallsDial } from '../../components/messenger/calls/dial.vue'
export { default as MessengerCalls } from '../../components/messenger/calls/index.vue'
export { default as MessengerCallsMissed } from '../../components/messenger/calls/missed.vue'
export { default as MessengerCallsReceived } from '../../components/messenger/calls/received.vue'
export { default as MessengerCommonDocumentslist } from '../../components/messenger/common/documentslist.vue'
export { default as MessengerCommonDropdown } from '../../components/messenger/common/dropdown.vue'
export { default as MessengerCommonProfile } from '../../components/messenger/common/profile.vue'
export { default as MessengerCommonShareddoc } from '../../components/messenger/common/shareddoc.vue'
export { default as MessengerCommonUserdropdown } from '../../components/messenger/common/userdropdown.vue'
export { default as MessengerContactsContactcontent } from '../../components/messenger/contacts/contactcontent.vue'
export { default as MessengerContacts } from '../../components/messenger/contacts/contacts.vue'
export { default as MessengerCustomizerChatwallpaper } from '../../components/messenger/customizer/chatwallpaper.vue'
export { default as MessengerCustomizerChoosecolor } from '../../components/messenger/customizer/choosecolor.vue'
export { default as MessengerCustomizerCustomizesetting } from '../../components/messenger/customizer/customizesetting.vue'
export { default as MessengerCustomizer } from '../../components/messenger/customizer/index.vue'
export { default as MessengerCustomizerLayout } from '../../components/messenger/customizer/layout.vue'
export { default as MessengerCustomizerSidebar } from '../../components/messenger/customizer/sidebar.vue'
export { default as MessengerLefsidebarChats } from '../../components/messenger/lefsidebar/chats.vue'
export { default as MessengerLefsidebarContactList } from '../../components/messenger/lefsidebar/contact_list.vue'
export { default as MessengerLefsidebarContacts } from '../../components/messenger/lefsidebar/contacts.vue'
export { default as MessengerLefsidebarDocument } from '../../components/messenger/lefsidebar/document.vue'
export { default as MessengerLefsidebarNotification } from '../../components/messenger/lefsidebar/notification.vue'
export { default as MessengerLefsidebarSettings } from '../../components/messenger/lefsidebar/settings.vue'
export { default as MessengerLefsidebarStatus } from '../../components/messenger/lefsidebar/status.vue'
export { default as MessengerModalsAudiocall1 } from '../../components/messenger/modals/audiocall1.vue'
export { default as MessengerModalsAudiocall2 } from '../../components/messenger/modals/audiocall2.vue'
export { default as MessengerModalsCodesnippets } from '../../components/messenger/modals/codesnippets.vue'
export { default as MessengerModalsCreatetodo } from '../../components/messenger/modals/createtodo.vue'
export { default as MessengerModalsGroupaudiocall } from '../../components/messenger/modals/groupaudiocall.vue'
export { default as MessengerModalsGroupvediocall } from '../../components/messenger/modals/groupvediocall.vue'
export { default as MessengerModalsNewCall } from '../../components/messenger/modals/newCall.vue'
export { default as MessengerModalsNewChat } from '../../components/messenger/modals/newChat.vue'
export { default as MessengerModalsNewContact } from '../../components/messenger/modals/newContact.vue'
export { default as MessengerModalsNotesmodal } from '../../components/messenger/modals/notesmodal.vue'
export { default as MessengerModalsPollModal } from '../../components/messenger/modals/pollModal.vue'
export { default as MessengerModalsSetreminder } from '../../components/messenger/modals/setreminder.vue'
export { default as MessengerModalsTodo } from '../../components/messenger/modals/todo.vue'
export { default as MessengerModalsVediocall } from '../../components/messenger/modals/vediocall.vue'
export { default as MessengerRightsidebar } from '../../components/messenger/rightsidebar/index.vue'
export { default as MessengerChatGroupChatGroupchatheader } from '../../components/messenger/chat/GroupChat/groupchatheader.vue'
export { default as MessengerChatGroupChatGroupchatuser } from '../../components/messenger/chat/GroupChat/groupchatuser.vue'
export { default as MessengerChatGroupChatGroupcustomchat } from '../../components/messenger/chat/GroupChat/groupcustomchat.vue'
export { default as MessengerChatDirectChatDirectchatheader } from '../../components/messenger/chat/DirectChat/directchatheader.vue'
export { default as MessengerChatDirectChatDirectchatuser } from '../../components/messenger/chat/DirectChat/directchatuser.vue'
export { default as MessengerChatDirectChatDirectcustomchat } from '../../components/messenger/chat/DirectChat/directcustomchat.vue'
export { default as MessengerChatOfficialChatOfficialchatheader } from '../../components/messenger/chat/OfficialChat/officialchatheader.vue'
export { default as MessengerChatOfficialChatOfficialchatuser } from '../../components/messenger/chat/OfficialChat/officialchatuser.vue'
export { default as MessengerChatOfficialChatOfficialcustomchat } from '../../components/messenger/chat/OfficialChat/officialcustomchat.vue'
export { default as MessengerContactsFriendContactFriendcontactchat } from '../../components/messenger/contacts/FriendContact/friendcontactchat.vue'
export { default as MessengerContactsFriendContactFriendcontactheader } from '../../components/messenger/contacts/FriendContact/friendcontactheader.vue'
export { default as MessengerContactsFriendContactFriendcontactuser } from '../../components/messenger/contacts/FriendContact/friendcontactuser.vue'
export { default as MessengerContactsOfficialContactOfficialcontactchat } from '../../components/messenger/contacts/OfficialContact/officialcontactchat.vue'
export { default as MessengerContactsOfficialContactOfficialcontactheader } from '../../components/messenger/contacts/OfficialContact/officialcontactheader.vue'
export { default as MessengerContactsOfficialContactOfficialcontactuser } from '../../components/messenger/contacts/OfficialContact/officialcontactuser.vue'
export { default as MessengerContactsGroupContactGroupcontactchat } from '../../components/messenger/contacts/GroupContact/groupcontactchat.vue'
export { default as MessengerContactsGroupContactGroupcontactheader } from '../../components/messenger/contacts/GroupContact/groupcontactheader.vue'
export { default as MessengerContactsGroupContactGroupcontactuser } from '../../components/messenger/contacts/GroupContact/groupcontactuser.vue'
export { default as MessengerLefsidebarSettingAccount } from '../../components/messenger/lefsidebar/setting/account.vue'
export { default as MessengerLefsidebarSettingChat } from '../../components/messenger/lefsidebar/setting/chat.vue'
export { default as MessengerLefsidebarSettingHelp } from '../../components/messenger/lefsidebar/setting/help.vue'
export { default as MessengerLefsidebarSettingIntegratin } from '../../components/messenger/lefsidebar/setting/integratin.vue'
export { default as MessengerRightsidebarFiles } from '../../components/messenger/rightsidebar/files/index.vue'
export { default as MessengerRightsidebarFilesLink } from '../../components/messenger/rightsidebar/files/link.vue'
export { default as MessengerRightsidebarFilesMedia } from '../../components/messenger/rightsidebar/files/media.vue'
export { default as MessengerRightsidebarNotes } from '../../components/messenger/rightsidebar/notes/index.vue'
export { default as MessengerRightsidebarReminder } from '../../components/messenger/rightsidebar/reminder/index.vue'
export { default as MessengerRightsidebarProfileCommongroup } from '../../components/messenger/rightsidebar/profile/commongroup.vue'
export { default as MessengerRightsidebarProfileContactinfo } from '../../components/messenger/rightsidebar/profile/contactinfo.vue'
export { default as MessengerRightsidebarProfile } from '../../components/messenger/rightsidebar/profile/index.vue'
export { default as MessengerRightsidebarProfilePersonalinfo } from '../../components/messenger/rightsidebar/profile/personalinfo.vue'
export { default as MessengerRightsidebarProfileSharedmedia } from '../../components/messenger/rightsidebar/profile/sharedmedia.vue'
export { default as MessengerRightsidebarProfileStarredmessages } from '../../components/messenger/rightsidebar/profile/starredmessages.vue'
export { default as MessengerRightsidebarProfileStatus } from '../../components/messenger/rightsidebar/profile/status.vue'
export { default as MessengerRightsidebarTodo } from '../../components/messenger/rightsidebar/todo/index.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
